# STILL UNDER DEVELOPMENT
version: "1.0"

services:

  postgres:
    command:
      - postgres
      - -c
      - max_connections=150
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - postgres:/var/lib/postgresql/data
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} | grep "accepting connections" || exit 1
      timeout: 2s
    image: postgres:16
    restart: always
    
  server:
    restart: always
    build: .

    #TODO: when we want to test our github repo code then 1) move to wsl  2) add repos to image via bind mount
    #TODO: when we want to import existing prefect.yml file then 1) create .env file  2) add command to config set the profile settings or copy there
    command: prefect server start
    ports:
      - 4200:4200
      - 8080:8080
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - prefect_config:/root/.prefect
      - prefect_development:/app/prefect_development
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_DATABASE_CONNECTION_URL: ${DB_CONNECTION_URL}
      PREFECT_SERVER_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
      PREFECT_API_URL: ${PREFECT_API_URL}

volumes:
  postgres:
  prefect_config:
  prefect_development: