name: 'jaffle_shop'

config-version: 2
version: '0.1'
require-dbt-version: [">=1.7.0", "<2.0.0"]

profile: 'dbt_learn'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: [directorypath]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
