dbt_learn:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}" # change
      role: analyst # must be created
      user: "{{ env_var('SNOWFLAKE_USER') }}" # change

      # # Keypair config
      # private_key_path: [path/to/private.key]
      # # or private_key instead of private_key_path
      # private_key_passphrase: [passphrase for the private key, if key is encrypted]
      # authenticator: username_password_mfa
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"  # change

      warehouse: dev_analyst_xs_wh # must be created
      threads: 16 # minimum default
      database: dev_analytics # must be created
      schema: public

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}" # change
      role: analyst # must be created
      user: "{{ env_var('SNOWFLAKE_USER') }}" # change

      # # Keypair config
      # private_key_path: [path/to/private.key]
      # # or private_key instead of private_key_path
      # private_key_passphrase: [passphrase for the private key, if key is encrypted]
      # authenticator: username_password_mfa
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"  # change
      
      warehouse: analyst_xs_wh # must be created
      threads: 16
      database: analytics # must be created
      schema: public
      
  target: dev