dbt_learn:
  outputs:
    dev:
      type: snowflake
      account: ${SNOWFLAKE_ACCOUNT} # change
      role: analyst # must be created
      user: ${SNOWFLAKE_USER} # change
      password: ${SNOWFLAKE_PASSWORD} # change
      warehouse: dev_analyst_xs_wh # must be created
      threads: 16 # minimum default
      database: dev_analytics # must be created
      schema: public
    # prod:
    #   type: snowflake
    #   account: ${SNOWFLAKE_ACCOUNT}
    #   role: analyst
    #   user: ${SNOWFLAKE_USER}
    #   password: ${SNOWFLAKE_PASSWORD}
    #   warehouse: analyst_xs_wh
    #   threads: 16
    #   database: analytics
    #   schema: public
  target: dev